# Autogenerated wrapper script for rwkv_cpp_jll for x86_64-linux-gnu
export rwkv

JLLWrappers.@generate_wrapper_header("rwkv_cpp")
JLLWrappers.@declare_library_product(rwkv, "librwkv.so")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        rwkv,
        "lib/librwkv.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
